{
 "title": "Not a bot stats",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "label": "Server",
    "query": "SELECT DISTINCT name FROM notabot_stats_server"
   }
  ]
 },
 "panels": [
  { "title": "General server stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Members",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT date, membercount FROM notabot_stats_server WHERE $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "Messages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT date, messagecount FROM notabot_stats_server WHERE $__timeFilter(date) "
    }
   ]
  },
  {
   "title": "Daily active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT date, COUNT(userid) FROM notabot_stats_server_users WHERE $__timeFilter(date) GROUP BY date"
    }
   ]
  },
  {
   "title": "Top reactions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT reaction, SUM(amount) FROM notabot_stats_server_reactions WHERE $__timeFilter(date) GROUP BY reaction ORDER BY 2 DESC LIMIT 10"
    }
   ]
  }
 ]
}