// <auto-generated />
using System;
using Lumen.Modules.NotABot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lumen.Modules.NotABot.Data.Migrations
{
    [DbContext(typeof(NotABotContext))]
    partial class NotABotContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("NotABot")
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lumen.Modules.NotABot.Common.Models.ServerChannelStats", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReactionCount")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Date", "ChannelId");

                    b.ToTable("ServerChannelStats", "NotABot");
                });

            modelBuilder.Entity("Lumen.Modules.NotABot.Common.Models.ServerReactionStats", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reaction")
                        .HasColumnType("text");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Date", "Reaction");

                    b.ToTable("ServerReactionStats", "NotABot");
                });

            modelBuilder.Entity("Lumen.Modules.NotABot.Common.Models.ServerStats", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemberCount")
                        .HasColumnType("integer");

                    b.Property<int>("MemberJoined")
                        .HasColumnType("integer");

                    b.Property<int>("MemberLeft")
                        .HasColumnType("integer");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReactionAdded")
                        .HasColumnType("integer");

                    b.Property<int>("ReactionRemoved")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Date");

                    b.ToTable("ServerStats", "NotABot");
                });

            modelBuilder.Entity("Lumen.Modules.NotABot.Common.Models.ServerUserStats", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int>("MessageCount")
                        .HasColumnType("integer");

                    b.Property<int>("ReactionCount")
                        .HasColumnType("integer");

                    b.HasKey("Id", "Date", "UserId");

                    b.ToTable("ServerUserStats", "NotABot");
                });
#pragma warning restore 612, 618
        }
    }
}
